### ISSUE TITLE
No coercion on default value comparisons

### ISSUE THREAD

**Issue by pringelmann** [Treora/redux-query-sync#15]
### Scenario:
I have some initial state in my redux store that is set to an empty array: `[]`
I set the `defaultValue` property accordingly to ensure that the corresponding url parameter is not visible should the initial state be equal to `[]`

### Expected behaviour:
If the initial state is indeed `[]` then the parameter should not be present:
`defaultValue: []`
`state: []`
`http://www.test.com`

### Observed behaviour:
If the initial state is set to `[]` then the parameter is present but it's value is an empty string:
`defaultValue: []`
`state: []`
`http://www.test.com?state=`

### Source of problem
The issue seems to stem from the value comparison in `handleStateUpdate`:
```
            if (value === defaultValue) {
                locationParams.delete(param);
            } else {
                locationParams.set(param, valueToString(value));
            }
```
If the `defaultValue` is a reference to an empty array, then the `===` operator will return false if it is compared to a different array instance.

### Potential solution
One way to mitigate this would be to cast both values as strings: `valueToString(value) === valueToString(defaultValue)`. 

@Treora Please share your thoughts :)

This is a great library by the way!

**Comment by Treora** [comment]
Your use case is totally valid, it would be nice to not insist on strict equality. Your proposed solution of comparing stringified values seems nice and simple. I would however like to think through whether it has consequences for other scenarios, and also I would like to have a simple mental model of how this module behaves, and apply that consistenly.

My approach has been that most of the module is concerned with actual values, and string (de)serialisation is only applied at the very edge. Comparing the serialisations changes this mental model, so the question is whether/how it could still be simple and coherent.

For example, would it be more logical to rename `defaultValue` to `defaultString`, and change the comparison to `valueToString(value) === defaultString`?

Note that there is also the idea to let one's initial redux state provide the default values (see #1), which would be good to keep in mind here, and makes the `defaultString` approach less attractive.

Since `defaultValue` really just means 'the value that corresponds to an absent parameter', would it make sense to consider it part of the serialisation itself? E.g. if `valueToString` returns `null`, the parameter is dropped. Vice versa, `stringToValue` is given null when the parameter is absent.

These are my raw thoughts. To get to a conclusion they need to be worked out a bit more, either by me or by others.

**Comment by pringelmann** [comment]
Those are all valid points. I did not consider the use case of providing default state from redux. I will use a forked version in my project in the meantime. Closing PR

**Comment by Treora** [comment]
I actually discovered a simple workaround for you, without need for a fork, when rereading the Readme:
> Note you could equally well put the conversion to and from the string in the selector and action
creator, respectively. The `defaultValue` should then of course be a string too.

So to have the `defaultValue` be matched against the string, you would just have to do the string conversion yourself. Refactor your options, putting your previous `stringToValue` and `valueToString` functions into the `action` and `selector` options instead:
```
{
    action: value => yourAction(yourStringToValue(value))
    selector: state => yourValueToString(yourSelector(state)),
    defaultValue: '[]',
}
```

For `valueToString` you might just be using the default (``value => `${value}` ``), and `yourStringToValue` is by default simply the identity function (`x => x`).

**Comment by Treora** [comment]
Closing this as the workaround seems a workable solution.
