### ISSUE TITLE
bulk dispatch doesn't fit for complex cases

### ISSUE THREAD

**Issue by dmitkataev** [Treora/redux-query-sync#18]
In function handleLocationUpdate we collect actions in an array and then dispatch all of them in a separate loop. The problem is that some params can depend on another. For example, we have a query params country and currency. Currency depends on country. But in current solution if you set country to a new value, the currency in its selector will still use an old value.
To solve this problem we need 1) dispatch an action right after we get new param value 2) somehow define an order of processing params - less depended first. This can be done manually writing params in necessary order in ReduxQuerySync config.

Any thoughts?

**Comment by Treora** [comment]
> 1) dispatch an action right after we get new param value
> 2) somehow define an order of processing params - less depended first

Do you mean both (1) and (2) need to happen, or either?

I am not sure why/whether (1) would be necessary: at least in theory it should be fine to first create all actions and then dispatch them, because they should read the Redux state only when they are being dispatched (in the reducers/thunks/...), and they will thus see the updates made by earlier actions.

Defining an order is an option, but feels a bit contrived. One other solution that comes to mind is to rather let the user specify a single action, which will get an object with all changed(?) params. You would specify the `action` in the top-level config rather than in each of the `params` configs. Not sure if this is a nice API, or what would be the desired semantics if actions are specified both at the top-level and for some individual parameters. But it seems a simple solution to give full freedom in how to handle location updates.

**Comment by dmitkataev** [comment]
>I am not sure why/whether (1) would be necessary:  at least in theory it should be fine to first create all actions and then dispatch them, because they should read the Redux state only when they are being dispatched (in the reducers/thunks/...)

But what if I don't use thunks and use plain actions instead?

>One other solution that comes to mind is to rather let the user specify a single action, which will get an object with all changed(?) params.

This is a good idea. It will allow us to update store once for all changes (performance gain!).

**Comment by Treora** [comment]
> But what if I don't use thunks and use plain actions instead?

Then the reducer should be the one reading the state, which will be the up-to-date state as it is at time of dispatch. If your action creators are reading the state, and assuming that your state will still be the same when the action will be dispatched, I think you are making too many assumptions and potentially fragile code. Or else I have misunderstood the idea behind Redux.

**Comment by Treora** [comment]
Closing this. In [this comment](https://github.com/Treora/redux-query-sync/pull/33#issuecomment-482052022) are some more thoughts about instead providing control over how dispatching multiple changes is concerted.
