### ISSUE TITLE
action needs not only value but a state too

### ISSUE THREAD

**Issue by dmitkataev** [Treora/redux-query-sync#19]
If url param is bind to some dynamic store state, then it's not enough to know only the value we also need some other info to set this value to appropriate state.
The solution is simple - pass a state to an action too.

**Comment by Treora** [comment]
> If url param is bind to some dynamic store state

Do you mean that depending on some context (I assume you are thinking of a url path), the action creator should emit a different action?

> The solution is simple - pass a state to an action too.

Could you elaborate what you mean with 'a state'? `store.getState()`? Or `location` or `location.state`? Or something else?

I have so far assumed one can use closures to add arguments to an action creator, e.g. instead of `action: actionCreator`, one would pass `action: value => actionCreator(value, readSomeContext())` to the config. If there is something that is widely useful to pass here, or that cannot easily be accessed from outside the module, we could as you suggest pass it as second parameter.

**Comment by dmitkataev** [comment]
> Do you mean that depending on some context (I assume you are thinking of a url path), the action creator should emit a different action?

Yes, I mean exactly this.

>Could you elaborate what you mean with 'a state'? store.getState()? Or location or location.state? Or something else?

I mean store.getState().

>one would pass action: value => actionCreator(value, readSomeContext()) to the config.

In this case readSomeContext function must have an access to a store state if an action requires some info from it. But it's not always possible.
If you define readSomeContext in the place you call ReduxQuerySync, yes you have an access to store. But if you have a big app and many url params, you would not define all of them in one place - it's better to define them in a place which they belongs to. It can look like this:
```
ReduxQuerySync({
    store,
    params: {
        ...feature1.urlParams,
        ...feature2.urlParams,
    }
});
```
In this case featureX.urlParams can access a store in two ways: 1) we make urlParams as function and pass a store as argument - acceptable way, but in my opinion is worse then just pass state to an action (passing state to an action is also used in thunk lib f.e.); 2) directly import store inside a file where feature.urlParams is defined - this is a bad idea to import store across allover the app.

**Comment by Treora** [comment]
> But if you have a big app and many url params, you would not define all of them in one place

Good point. It would be much cleaner indeed if the options can be defined in isolation. A good reason to pass things like the `store`, `state` or `getState` (or perhaps other things like `location`) as an argument to the action creator, if they are likely needed there.

The remaining question however is whether or not they are likely needed there. As just discussed in #18, it seems inappropriate to read the Redux state inside an action creator; state should only be read during dispatch (normally by a reducer), to ensure it is the actual state and thereby make things like reverting and replaying actions work as expected. Passing state to action creators would thus only encourage bad patterns.

Adhering to this principle suggests that the choice of which action to dispatch cannot depend on the state itself. Instead, the same action should always be dispatched, and the difference in behaviour should be achieved by making the reducers behave in a way that depends on the state that they observe.

I agree this does not feel as intuitive; I'd rather dispatch different actions. Not yet sure what is a sensible solution here.

**Comment by Treora** [comment]
Getting more philosophical... (consider this a note to myself, really)

I am not sure how the theoretical model of an application as a sequence of state updates should deal with user interaction in general, and specifically with a location bar (that has a piece of state and an update mechanism by itself). Thinking about it, I start to realise we might already be on the wrong track by passing the query parameters to the action creator when for example the user presses the browser's 'back' button. Those parameters are actually part of the state (of the location bar).

Imagine we revert the application state, modify some parameter, and replay all the actions. Then dispatching the 'back action' again would not necessarily lead to the same state that pressing the back button would lead to, since the action object contains a target that was created in a different branch of history.

So ideally (I guess) we would not put the location in the action, but just the fact that the back button was pressed, and let our reducers determine the new location. We would then treat the location bar somewhat like React treats the DOM: as a stateful thing that we control such that it appears stateless. I wonder if existing routers can already do this. Might be a fun follow-up project.

Our approach might actually be somewhat on the clean side already, as the actions only contain the changed parameter. So if an action `{type: 'setDestination', payload: 'Brussels'}` would be dispatched again onto a different, modified branch of application history, it would at least keep all other parameters intact.

**Comment by dmitkataev** [comment]
>it seems inappropriate to read the Redux state inside an action creator; state should only be read during dispatch (normally by a reducer)

```
const countryReducer = (state = {}, action) => {
  switch(action.type) {
     case 'SET_COUNTRY':
         return action.country;
     default:
         return state;
  }
};

const sortReducer = (state = { field: 'some', direction: 'asc' }, action) => {
   switch(action.type) {
     case 'SET_SORT_FIELD':
       return { ...state, field: action.field }
     default: 
       return state;
   }
};

const customersByCountryReducer = (state = {}, action) => {
   if (!action.country) { return state; }
   return {
       ...state,
       [action.country]: sortReducer(state[action.country], action),
   };
};

const reducer = combineReducers({
  country: countryReducer,
  customersByCountry: customersByCountryReducer,
});

// here is a plain action creator
const setSortField = (country, field) => ({
   type:  'SET_SORT_FIELD',
   country,
   field,
});

ReduxQuerySync({
  country: {
    selector: getCountry,
    action: setCountry,
  },
  sortField: {
    selector: getSortField(state),
    action: value => setSortField(???, value) // where to get country?
// action: (value, state) => setSortField(getCountry(state), value)
  }
})
```
This code is just to illustrate the case.

**Comment by Treora** [comment]
Thanks for sharing, it helps having some actual code to look at. I would refactor such that `getCountry(state)` is performed inside the reducer. It is state, so it can be read by reducers. The only reason it cannot, in your case, is that you are using `combineReducers` to treat the two subreducers independently, But apparently they are not  independent, as one needs to know the state of the other. Refactoring the reducer structure would seem much cleaner than taking the logic outside of the reducers.

**Comment by dmitkataev** [comment]
>Refactoring the reducer structure would seem much cleaner than taking the logic outside of the reducers.

I knew you say so. I've already tried this way of organizing state and I didn't like this - you have too tight state parts, which break a code re-use paradigm. But this issue is not about architecting the  state. 

In issue #17 you wrote
>To keep this module modular, and not attempt to become a full router (feel free to fork and do that!), I would prefer to remain unopinionated about anything besides query parameters.

But now you say that users must have an appropriate state structure to use the lib. :)

I think it would be much more modular to give an access to state in method which construct an action.

**Comment by Treora** [comment]
> But now you say that users must have an appropriate state structure to use the lib. :)

I am also opinionated about being unopinionated, how about that. :)

Maybe encountering other examples by more people it might make me think differently, but so far adding state as an argument seems to just encourage bad coding practices. I hope you are okay with closing this until then.

> I've already tried this way of organizing state and I didn't like this - you have too tight state parts, which break a code re-use paradigm

As for that, the state itself needs no reorganisation. Just the reducers, but probably that's what you meant. There are many ways to refactor it. I am not recommending it, but you could even keep your reducers exactly the same, and add a top level reducer that inserts the `country` into the action object if needed. Only slightly less ugly, you could have such a top level reducer add the whole `state` to the action object, so that a reducer that gets only one branch of the `state` object can call `getCountryCode(action.wholeState)`. Just trying to think along.
