### ISSUE TITLE
Explain where the `store` variable comes from in the docs example

### ISSUE THREAD

**Issue by nhooey** [Treora/redux-query-sync#20]
The example is missing context for the `store` object, among other things.

Adding more context so the code works immediately would be helpful.

**Comment by Treora** [comment]
Thanks for noticing. I updated the example's comments (in commit 90e9769) to make it clearer that you have to pass your own Redux store, action creator and selector function. I hope that helps readers realise that they have to set up their Redux before using this module. It is assumed readers are already familiar with Redux, introducing every piece of it seems out of scope. Since the config is specific to the user's Redux configuration, a piece of code that immediately works for people seems impossible. A tiny example application would then be more useful, as you noted in #21.
