### ISSUE TITLE
add `debounce` option to improve performance for high-volume actions

### ISSUE THREAD

**Issue by nickav** [Treora/redux-query-sync#24]
This would be really nice to have either for the entire config or for a given action. Right now if the `action` method returns null then an error about no property `type` is thrown. By allowing the `action` function to return null, this could enable a custom-built debounce solution. One built-in would be even better

**Comment by Treora** [comment]
I am not entirely sure I understand the problem here; is the situation you have in mind one where many quick changes in the location occur, and therefore many actions are dispatched? Are there situations in practice that would make this happen?

I would suspect that the reverse situation is more common, that a value in the state changes very often, but one might not want to update the location with the same frequency.

Either way, my intention has been to keep the state and location as tightly in sync as possible, to minimise the durations of inconsistency between state and location, and thereby reduce the possibilities for tricky edge cases and race conditions to creep in. Although this principle may already be compromised somewhat, debouncing actions sounds like it would lead to longer inconsistencies between the two, so I would at least have to see an actual scenario to be convinced it is a good idea.

**Comment by Treora** [comment]
Closing this while need for it is unclear. If there is a need, the suggested change to simply skip a dispatch if an action creator returns `null` seems easy to make. While there appears no use case however, I rather have an error be thrown as it helps reveal mistakes.
