### ISSUE TITLE
defaultValue prevents a url parameter from being created

### ISSUE THREAD

**Issue by david-house-harvard** [Treora/redux-query-sync#28]
Hi there,

One odd gotcha that I found is that the conditional [here](https://github.com/Treora/redux-query-sync/blob/master/src/redux-query-sync.js#L121) makes for confusing behavior in the following circumstance:

1. A query parameter is absent from the URL when its associated action creator is dispatched
2. The value in the state is the same as the `defaultValue` supplied to `ReduxQuerySync

In this situation, `locationParams` never has its value set, so [the url is never updated](https://github.com/Treora/redux-query-sync/blob/master/src/redux-query-sync.js#L132).

It would be helpful if there could be an additional check here to see if the query parameter is present in the actual URL. I'm happy to put out a PR for this, if you like.

Thanks for all of your work on this!

**Comment by Treora** [comment]
Hi; from reading your description I am not sure if this gotcha you describe is intended behaviour, or if you found a bug.

If you end up with a situation where the url is not updated, but the value in the state is not equal to its `defaultValue`, then we clearly have a bug. Let me know if that is the case.

If you set a value to equal its `defaultValue`, the intention is that it is not displayed in the URL. Even if it was already displayed, it will then become hidden. If this intended behaviour appears to you as a gotcha, than we don't have a bug, but you are welcome to suggest what kind of behaviour would seem more logical to you! (alternatives I could come up with have the unpleasant side-effect of breaking the one-to-one mapping between state and URL)

**Comment by david-house-harvard** [comment]
> If you set a value to equal its defaultValue, the intention is that it is not displayed in the URL. Even if it was already displayed, it will then become hidden. 

This is what confuses me. If there's supposed to be a one-for-one mapping between url parameters and the state, and the subscribed state property has it's value set, shouldn't that state value _always_ be reflected in the URL?

Edit: Or is the intention of `defaultValue` to reduce the potential size of the URL by saying "hey, if the state already reflects my default value, there's no need to duplicate the state value."

**Comment by Treora** [comment]
I understand your confusion. The `defaultValue` is indeed perhaps better regarded as telling which value should correspond to absence of the parameter. Maybe we should rename it to `valueCorrespondingToAbsentParameter`. :)

In cases where the state should have some actual default value (in the usual sense of the word), but you *do* want that value to be displayed in the URL, you can simply leave `defaultValue` to be `undefined`. When visiting the page without specifying the parameter, the sync will then call `action(undefined)` (assuming `initialTruth`=`'location'`). Your reducer should then be slightly disobedient and set the actual default value in the state (rather than setting it to `undefined`). The disobedience will subsequently be observed by the state-to-location syncer, and the location will be updated to reflect the new state. Hope this helps.

**Comment by david-house-harvard** [comment]
Yes, that definitely helps. Thanks for talking this through! I was able to achieve my intended results by simply omitting `defaultValue`, as you suggest :)
