### ISSUE TITLE
Investigate location pushes on initialisation

### ISSUE THREAD

**Issue by Treora** [Treora/redux-query-sync#5]
As [reported](https://github.com/Treora/redux-query-sync/pull/4#discussion_r129821905) by @riccardoscalco: 

> I see an unexpected behaviour(`initialTruth: 'location'` and `defaultValue: undefined`): the user can repeatedly click on the browser back arrow and it remains active.

This sounds like on initialisation, `handleStateUpdate` is triggered (as expected) and ends up with a `newLocationSearchString` different from `oldLocationSearchString`, and thus [calls]((https://github.com/Treora/redux-query-sync/blob/fb6f57d27c7030a9202a54e619fc21d5be5758b9/src/redux-query-sync.js#L112)) `locationUpdate` (=`history.pushState`), thus directly creating a new history entry. The question is why the state is different than expected.

One possible problem I just realised, that could be causing this: when multiple parameters are synced, actions are dispatched in sequence, and a `handleStateUpdate` might be triggered after each of them. After e.g. the first of two such actions, `handleStateUpdate` would trigger and still find an old value of the second parameter in the state, and update the location to match it. Then the second action should update it in the state and which causes a final update in the location again, so if I am not mistaken it ends up fine, but with some undesired history entries.

@riccardoscalco: It would be interesting to know if your described problem also appears if you have only one parameter in the configuration. There could well be other mistakes that cause this issue.

I should scrutinise the exact flows of actions and updates some time soon. If in the meantime anyone figures out either the problem or solution, give a shout.

**Comment by riccardoscalco** [comment]
[Here](https://github.com/riccardoscalco/redux-query-sync-issue-5) there is a toy application where you can see the issue.

I must say I am not sure if the issue is on redux-query-sync or in the toy application.

You should see the issue with the following steps:
* open a tab
* go to google.com
* on the same tab load the app writing "localhost:8080" in the URL bar
* click multiple times on the "go back" browser arrow

I would expect to go back to google.com.
Note that the expected behaviour happens when `defaultValue` is set to `1` in `store.js` or `dispatchInit` is commented in `index.js` or both.

Moreover, a different issue happens when `dispatchInit` is commented in `index.js` and `defaultValue` is set to `undefined`:

* open a tab
* go to google.com
* on the same tab load the app writing "localhost:8080" in the URL bar
* click button 2 (the url now has "/?f=2")
* click on the "go back" browser arrow

I would say the expected behaviour is to go back to localhost:8080.

**Comment by Treora** [comment]
@riccardoscalco: Thanks for the nicely organised toy application and problem descriptions, really helpful! 

The toy application was fine. The initialisation behaviour of redux-query-sync needed to be better thought through though. I think PR #6 fixes all the concerns, at least the toy app seems to work nicely now. I'd be glad to hear if you still find quirks.

Perhaps different from your expectations, going to `localhost:8080` will now directly change its location to include `?f=1`; this because your reducer does not allow the initialisation to set `undefined` as a value. In this scenario, the logical solution is to update the URL, so they are in sync again. By doing this with `replaceState: true` this does not create a history entry. To keep the query parameters empty when they were originally empty, ensure that your `defaultValue`s are valid values; and probably you would want these to be the store's initial values.

**Comment by riccardoscalco** [comment]
Thanks for the fixes, everything works as I would expect.

Having `?f=1` in the location when `defaultValue` is `undefined` is fine with me, the location is changed according to the default state in the reducer.
