### ISSUE TITLE
how to modify other url parts, not only query params?

### ISSUE THREAD

**Issue by dmitkataev** [Treora/redux-query-sync#9]
Hi! How can I change other parts of url, not only query params? Why do you use internal browser history and do not allow to pass it as a parameter?

**Comment by Treora** [comment]
This module is focussed just on query parameters. It tries to not make assumptions about things outside its scope, so it may be possible to combine it with tools that do change other parts of the URL (path and hash). Some tools (often called routers) may manage all of them at once, which you might prefer; consider e.g. [react-router](https://reacttraining.com/react-router/) in combination with [react-router-redux-sync](https://github.com/scienceai/react-router-redux-sync).

Regarding your second question, you mean to allow passing the `history` object instead of always getting it from `createHistory`? This could be changed, if anyone feels like testing it.

**Comment by dmitkataev** [comment]
I understood that this module focused on query params, but what if url is changed by the react-router? The module dosn't track this change and when you do next change of any parameter, the base part of url changed by react-router will be replaced by the previous one.
For example: 
test.com/tab1?q=1
change url by the react-router to test.com/tab2?q=1
then set q param to value 2
the result is test.com/tab1?q=2
That's because of two different history object.  And it was the reason why I asked about passing history as a parameter of module.

**Comment by Treora** [comment]
Ok, that is a problem indeed. I had not tested this combination but I thought it should work, but apparently made a wrong assumption about how the history module works internally (I would expect it to always reread the location, rather than trusting that it remained the same). Will propose a fix.

**Comment by dmitkataev** [comment]
if you don't mind I make a pull request. I've already done this.

**Comment by Treora** [comment]
Ah, I just did too, sorry. You're still welcome to send your PR though; especially if you feel like updating the docs. :)

**Comment by Treora** [comment]
Fixed by #11.
